version: '3.3'
secrets:
  rltheme_mysql_root: 
    external: true
  rltheme_mysql_user:
    external: true
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - rltheme_mysql_root
      - rltheme_mysql_user
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/rltheme_mysql_user
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/rltheme_mysql_root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    secrets:
      - rltheme_mysql_user
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/rltheme_mysql_user
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
    db_data: